// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkApplicationExistsByName = `-- name: CheckApplicationExistsByName :one
SELECT EXISTS (
    SELECT 1 FROM applications WHERE name = $1
) AS exists
`

func (q *Queries) CheckApplicationExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkApplicationExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (id, project_id, name, description, repo_url, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, description, repo_url, created_at
`

type CreateApplicationParams struct {
	ID          uuid.UUID
	ProjectID   int32
	Name        string
	Description sql.NullString
	RepoUrl     sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.RepoUrl,
		arg.CreatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteApplicationByName = `-- name: DeleteApplicationByName :exec
DELETE FROM applications
WHERE name = $1
`

func (q *Queries) DeleteApplicationByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteApplicationByName, name)
	return err
}

const getApplicationByName = `-- name: GetApplicationByName :one
SELECT id, project_id, name, description, repo_url, created_at FROM applications
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetApplicationByName(ctx context.Context, name string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByName, name)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestApplicationVersionByApplicationName = `-- name: GetLatestApplicationVersionByApplicationName :one
SELECT av.id, av.application_id, av.version, av.git_hash, av.description, av.created_at FROM application_versions av
JOIN applications a ON av.application_id = a.id
WHERE a.name = $1
ORDER BY av.created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestApplicationVersionByApplicationName(ctx context.Context, name string) (ApplicationVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestApplicationVersionByApplicationName, name)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.GitHash,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProjectApplications = `-- name: ListAllProjectApplications :many
SELECT id, project_id, name, description, repo_url, created_at FROM applications
WHERE project_id = (
  SELECT id FROM projects WHERE projects.name = $1
)
`

func (q *Queries) ListAllProjectApplications(ctx context.Context, name string) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjectApplications, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.RepoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
