// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Application struct {
	ID          uuid.UUID
	ProjectID   int32
	Name        string
	Description sql.NullString
	RepoUrl     sql.NullString
	CreatedAt   time.Time
}

type ApplicationVersion struct {
	ID            uuid.UUID
	ApplicationID uuid.UUID
	Version       string
	GitHash       sql.NullString
	Description   sql.NullString
	CreatedAt     time.Time
}

type Project struct {
	ID          int32
	Name        string
	Link        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
}

type ProjectVersion struct {
	ID          uuid.UUID
	ProjectID   int32
	Version     string
	Description sql.NullString
	CreatedAt   time.Time
}

type ProjectVersionApp struct {
	ProjectVersionID     uuid.UUID
	ApplicationID        uuid.UUID
	ApplicationVersionID uuid.UUID
}
